#!/usr/bin/lua

local inner_radius = 60
local outer_radius = 35

local x, y = 128, 128

for i = 0, 23 do
   local angle = (7 + 15*i)/180*math.pi
   local radius
   if i%2 == 0 then
      radius = inner_radius
   else
      radius = outer_radius
   end
   print (tostring (x + math.cos (angle)*radius)..","..tostring (y - math.sin (angle)*radius))
end
